tasks:
  - before: >
      wget -qOdatabase-setup.sh https://codejudge-starter-repo-artifacts.s3.ap-south-1.amazonaws.com/gitpod/backend/python/gitpod-setup.sh &&
      chmod 0755 database-setup.sh &&
      bash database-setup.sh 3.5.3
    init: |
      pip install --upgrade pip
      python -m pip install Django==2.1 pytz==2019.2
      pip install -r requirements.txt
      python manage.py migrate
    command: python manage.py runserver 0.0.0.0:8080
ports:
  - port: 8080
    name: "Backend Server"
    onOpen: open-browser
    visibility: public
  - port: 3306
    name: "MySQL Server"
    onOpen: ignore
    visibility: public
  - port: 27017
    name: "MongoDB Server"
    onOpen: ignore
    visibility: public

vscode:
  extensions:
    - ms-python.python
